package no.ssb.ppi.connection;

/**
 *  An APChkException is created whenever an error is reported on the 
 *  server. See accessPoint Server documentation for details about server generated 
 *  errors. accessPoint server errors have both an error code and a string message.
 */
public class APChkException extends Exception{
	private int _errorCode;
	private String _errorMessage;

	/**
	 * Standard constructor using only a string
	 */
	public APChkException(String msg){
		super(msg);
	}

	/**
	 *  Constructor based on code and message produced by the server. Note 
	 *  that the regular Exception.getMessage() will contain both the code 
	 *  and the message.
	 *
	 *  @param code error code generated by accessPoint server
	 *  @param msg error message generated by the accessPoint server
	 */
	public APChkException(int code, String msg){
		super("accessPoint error code " + code + " was returned: " + msg);
		_errorCode = code;
		_errorMessage = msg;
	}

	/**
	 *  Gets the server generated error code.
	 *
	 *  @return server generated error code or -1 for client side errors
	 */
	public int getaccessPointErrorCode(){
		return _errorCode;
	}

	/**
	 *  Gets the server generated error message.
	 * 
	 *  @return server generated error message
	 */
	public String getaccessPointErrorMessage(){
		return _errorMessage;
	}
}
